CREATE DATABASE DB_RESTAURANTE;
USE DB_RESTAURANTE;

CREATE TABLE TB_LOGIN(
	ID INT IDENTITY (1,1),
    USUARIO VARCHAR(40) UNIQUE NOT NULL,
    SENHA VARCHAR(30) NOT NULL,
	PRIMARY KEY(ID)
);

INSERT INTO TB_LOGIN (USUARIO, SENHA) VALUES('Felipe','123456');

SELECT *FROM TB_LOGIN;

CREATE TABLE TB_FUNCIONARIO(
	ID INT IDENTITY (1,1) PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	RG VARCHAR(11) NOT NULL,
	TEL VARCHAR(11) NOT NULL,
	CPF VARCHAR(14) NOT NULL,
	ENDERECO VARCHAR(100) NOT NULL,
	ID_FUNC VARCHAR(4) NOT NULL,
	BANCO VARCHAR(50) NOT NULL,
	CONTA VARCHAR(14) NOT NULL,
	AGENCIA VARCHAR (20) NOT NULL
);

SELECT *FROM TB_FUNCIONARIO;

CREATE TABLE TB_PRODUTOS(
	ID INT IDENTITY (1,1) PRIMARY KEY,
	CODIGO INT NOT NULL,
	PRODUTO VARCHAR (100) NOT NULL,
	PRECO VARCHAR(20) NOT NULL,
	ESTOQUE VARCHAR(50) NOT NULL,
	TIPO VARCHAR(20) NOT NULL,
	UNID_MEDIA INT
	);

SELECT * FROM TB_PRODUTOS;

DELETE FROM TB_PRODUTOS WHERE ID = 2;